//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bd.Icm.DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentCommit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstrumentCommit()
        {
            this.Parts = new HashSet<Part>();
            this.PartActions = new HashSet<PartAction>();
            this.PartMetadatas = new HashSet<PartMetadata>();
        }
    
        public int Id { get; set; }
        public int InstrumentId { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public byte[] RowVersion { get; set; }
        public int Revision { get; set; }
        public int EffectiveTo { get; set; }
    
        public virtual InstrumentVersion InstrumentVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Parts { get; set; }
        public virtual User Creator { get; set; }
        public virtual User Modifier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartAction> PartActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartMetadata> PartMetadatas { get; set; }
    }
}
