//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bd.Icm.DataAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Id { get; set; }
        public int RowVersion { get; set; }
        public Nullable<int> ParentPartId { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> DashNumber { get; set; }
        public int RevisionNumber { get; set; }
        public string SapPartNumber { get; set; }
        public int SapPartType { get; set; }
        public string LotCode { get; set; }
        public string DateCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public int EffectiveFrom { get; set; }
        public int EffectiveTo { get; set; }
        public string Description { get; set; }
        public Nullable<int> InstrumentCommitId { get; set; }
        public int ModificationType { get; set; }
        public string MfgPartNumber { get; set; }
        public string DocumentNumber { get; set; }
        public string Manufacturer { get; set; }
    
        public virtual InstrumentCommit InstrumentCommit { get; set; }
        public virtual InstrumentVersion InstrumentVersion { get; set; }
        public virtual PartVersion PartVersion { get; set; }
        public virtual PartVersion PartVersion1 { get; set; }
        public virtual User Creator { get; set; }
        public virtual User Modifier { get; set; }
    }
}
